import {
    GET_ALL_USERS,
    GET_SPECIFIC_USER,
    GET_USER_ID,
    GET_SERIEL_NUMBER,
    GET_MANUFACTURER,
    GET_MODEL,
    GET_COMPUTER_NAME,
    GET_LOCATION,
    GET_OPERATING_SYSTEM,
    GET_OS_ARCHITCHRE,
    GET_TOTAL_SYSTEM_MEMORY,
    GET_VIDEO,
    GET_VIDEO_MEMORY,
    GET_DNS_DOMAIN,
    GET_LAST_KNOWN_IP,
    GET_MAC
} from '../constantts';
